---
- name: Install Apache on RedHat and Debian
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Apache on RedHat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache on Debian
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Apache on RedHat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable Apache on Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
    